package the.bhushan.service.record;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T14:40:18.957+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.openmeetings.apache.org/", name = "RecordingWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface RecordingWebService {

    @WebMethod
    @RequestWrapper(localName = "getExternal", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternal")
    @ResponseWrapper(localName = "getExternalResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.record.RecordingDTO> getExternal(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "externaltype", targetNamespace = "")
        java.lang.String externaltype,
        @WebParam(name = "externalid", targetNamespace = "")
        java.lang.String externalid
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getExternalByRoom", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternalByRoom")
    @ResponseWrapper(localName = "getExternalByRoomResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternalByRoomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.record.RecordingDTO> getExternalByRoom(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "roomid", targetNamespace = "")
        java.lang.Long roomid
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getExternalByType", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternalByType")
    @ResponseWrapper(localName = "getExternalByTypeResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.GetExternalByTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.record.RecordingDTO> getExternalByType(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "externaltype", targetNamespace = "")
        java.lang.String externaltype
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.record.DeleteResponse")
    public void delete(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    ) throws ServiceException_Exception;
}
