package the.bhushan.service.record;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T14:40:19.019+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "org.apache.openmeetings.webservice.RecordingWebService", 
                  wsdlLocation = "file:/tmp/recordservice.wsdl",
                  targetNamespace = "http://webservice.openmeetings.apache.org/") 
public class RecordingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.openmeetings.apache.org/", "org.apache.openmeetings.webservice.RecordingWebService");
    public final static QName RecordingWebServicePort = new QName("http://webservice.openmeetings.apache.org/", "RecordingWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/tmp/recordservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecordingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/tmp/recordservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecordingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecordingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RecordingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RecordingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RecordingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RecordingWebService
     */
    @WebEndpoint(name = "RecordingWebServicePort")
    public RecordingWebService getRecordingWebServicePort() {
        return super.getPort(RecordingWebServicePort, RecordingWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordingWebService
     */
    @WebEndpoint(name = "RecordingWebServicePort")
    public RecordingWebService getRecordingWebServicePort(WebServiceFeature... features) {
        return super.getPort(RecordingWebServicePort, RecordingWebService.class, features);
    }

}
