package the.bhushan.service.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T00:57:12.220+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.openmeetings.apache.org/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.UserDTO add(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "user", targetNamespace = "")
        the.bhushan.service.user.UserDTO user,
        @WebParam(name = "confirm", targetNamespace = "")
        java.lang.Boolean confirm
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.user.UserDTO> get(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "kick", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Kick")
    @ResponseWrapper(localName = "kickResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.KickResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.ServiceResult kick(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "publicsid", targetNamespace = "")
        java.lang.String publicsid
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "count", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.CountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int count(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "roomid", targetNamespace = "")
        java.lang.Long roomid
    );

    @WebMethod
    @RequestWrapper(localName = "getRoomHash", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.GetRoomHash")
    @ResponseWrapper(localName = "getRoomHashResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.GetRoomHashResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.ServiceResult getRoomHash(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "user", targetNamespace = "")
        the.bhushan.service.user.ExternalUserDTO user,
        @WebParam(name = "options", targetNamespace = "")
        the.bhushan.service.user.RoomOptionsDTO options
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.ServiceResult delete(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteExternal", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.DeleteExternal")
    @ResponseWrapper(localName = "deleteExternalResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.DeleteExternalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.ServiceResult deleteExternal(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "externaltype", targetNamespace = "")
        java.lang.String externaltype,
        @WebParam(name = "externalid", targetNamespace = "")
        java.lang.String externalid
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.user.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.user.ServiceResult login(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass
    );
}
