package the.bhushan.service.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T00:57:12.249+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "org.apache.openmeetings.webservice.UserWebService", 
                  wsdlLocation = "file:/tmp/userservice.wsdl",
                  targetNamespace = "http://webservice.openmeetings.apache.org/") 
public class UserWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.openmeetings.apache.org/", "org.apache.openmeetings.webservice.UserWebService");
    public final static QName UserService = new QName("http://webservice.openmeetings.apache.org/", "UserService");
    static {
        URL url = null;
        try {
            url = new URL("file:/tmp/userservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/tmp/userservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserService")
    public UserService getUserService() {
        return super.getPort(UserService, UserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserService")
    public UserService getUserService(WebServiceFeature... features) {
        return super.getPort(UserService, UserService.class, features);
    }

}
