package the.bhushan.service.room;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T01:07:29.778+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.openmeetings.apache.org/", name = "RoomWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface RoomWebService {

    @WebMethod
    @RequestWrapper(localName = "getExternal", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetExternal")
    @ResponseWrapper(localName = "getExternalResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetExternalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.RoomDTO getExternal(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "externaltype", targetNamespace = "")
        java.lang.String externaltype,
        @WebParam(name = "externalid", targetNamespace = "")
        java.lang.Long externalid,
        @WebParam(name = "room", targetNamespace = "")
        the.bhushan.service.room.RoomDTO room
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.RoomDTO add(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "room", targetNamespace = "")
        the.bhushan.service.room.RoomDTO room
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "counters", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Counters")
    @ResponseWrapper(localName = "countersResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.CountersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.room.RoomCountBean> counters(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        java.util.List<java.lang.Long> id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "kick", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Kick")
    @ResponseWrapper(localName = "kickResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.KickResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.ServiceResult kick(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPublic", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetPublic")
    @ResponseWrapper(localName = "getPublicResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetPublicResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<the.bhushan.service.room.RoomDTO> getPublic(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getRoomById", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetRoomById")
    @ResponseWrapper(localName = "getRoomByIdResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.GetRoomByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.RoomDTO getRoomById(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "open", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Open")
    @ResponseWrapper(localName = "openResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.OpenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.ServiceResult open(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "close", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.CloseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.ServiceResult close(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webservice.openmeetings.apache.org/", className = "the.bhushan.service.room.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public the.bhushan.service.room.ServiceResult delete(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws ServiceException_Exception;
}
