package the.bhushan.service.room;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-11T01:07:29.835+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "org.apache.openmeetings.webservice.RoomWebService", 
                  wsdlLocation = "file:/tmp/room.wsdl",
                  targetNamespace = "http://webservice.openmeetings.apache.org/") 
public class RoomServiceStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.openmeetings.apache.org/", "org.apache.openmeetings.webservice.RoomWebService");
    public final static QName RoomWebServicePort = new QName("http://webservice.openmeetings.apache.org/", "RoomWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/tmp/room.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RoomServiceStub.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/tmp/room.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RoomServiceStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoomServiceStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomServiceStub() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RoomServiceStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RoomServiceStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RoomServiceStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RoomWebService
     */
    @WebEndpoint(name = "RoomWebServicePort")
    public RoomWebService getRoomWebServicePort() {
        return super.getPort(RoomWebServicePort, RoomWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomWebService
     */
    @WebEndpoint(name = "RoomWebServicePort")
    public RoomWebService getRoomWebServicePort(WebServiceFeature... features) {
        return super.getPort(RoomWebServicePort, RoomWebService.class, features);
    }

}
